### ISSUE TITLE
Base Path Rewrite: Error on Kibana v6 to v6.7.1

### ISSUE THREAD

**Issue by nikolay** [pjhampton/kibana-prometheus-exporter#58] opened 2019-02-26 03:31 UTC
I keep getting `TypeError: Uncaught error: Cannot read property 'overall' of undefined`.

**Comment by pjhampton** [comment] 2019-02-26 19:57
@nikolay Hey. I can't reproduce for some reason. I `g pull`'ed from master and installed over `kibana-plugin`

I do see a call here, but I would have imagined that function would have returned 0. Is there anything that you could have changed on your end?

```
- 31 function convert_state_to_number(state) {
- 32     if (state == 'green') {
2 33         return 1;
2 34     }
- 35     else if (state == 'yellow') {
2 36         return 0.5;
2 37     }
- 38     else {
2 39         return 0;
2 40     }
| 41 }
```

Can you please describe your environment and please dump the contents from: `<host etc>/api/status?extended`?

**Comment by nikolay** [comment] 2019-02-26 23:33
@pjhampton I am using this in Kubernetes and it hasn't been working since we upgraded to Elastic v6 as far as I can recall. I am not familiar with Kibana plugin development, but can't you get the [Status](https://github.com/elastic/kibana/blob/6.6/src/server/status/status.js) object from the server without having to go thru the whole REST API layer, which would make this faster and less prone to error, and, also, you won't have to bother with authentication and so on?

**Comment by pjhampton** [comment] 2019-02-27 09:09
Hey @nikolay 

I'm afraid not, no. I have already experimented with this and to make that work I would have to create a circular dependency. I have had similar reports that people are having similar problems behind an nginx reverse proxy. Can you give me more info on kubernetes?

**Comment by nikolay** [comment] 2019-04-09 00:30
Here's what's in the logs:

```json
{"type":"response","@timestamp":"2019-04-09T00:01:45Z","tags":[],"pid":1,"method":"get","statusCode":404,"req":{"url":"/kibana/api/status?extended=","method":"get","headers":{"host":"0:5601","accept":"application/json","connection":"close"},"remoteAddress":"127.0.0.1","userAgent":"127.0.0.1"},"res":{"statusCode":404,"responseTime":0,"contentLength":9},"message":"GET /kibana/api/status?extended= 404 0ms - 9.0B"}
{"type":"error","@timestamp":"2019-04-09T00:01:45Z","tags":[],"pid":1,"level":"error","error":{"message":"404 - {\"statusCode\":404,\"error\":\"Not Found\",\"message\":\"Not Found\"}","name":"StatusCodeError","stack":"StatusCodeError: 404 - {\"statusCode\":404,\"error\":\"Not Found\",\"message\":\"Not Found\"}\n    at new StatusCodeError (/usr/share/kibana/plugins/kibana-prometheus-exporter/node_modules/request-promise-core/lib/errors.js:32:15)\n    at Request.plumbing.callback (/usr/share/kibana/plugins/kibana-prometheus-exporter/node_modules/request-promise-core/lib/plumbing.js:104:33)\n    at Request.RP$callback [as _callback] (/usr/share/kibana/plugins/kibana-prometheus-exporter/node_modules/request-promise-core/lib/plumbing.js:46:31)\n    at Request.self.callback (/usr/share/kibana/node_modules/request/request.js:185:22)\n    at Request.emit (events.js:189:13)\n    at Request.<anonymous> (/usr/share/kibana/node_modules/request/request.js:1161:10)\n    at Request.emit (events.js:189:13)\n    at IncomingMessage.<anonymous> (/usr/share/kibana/node_modules/request/request.js:1083:12)\n    at Object.onceWrapper (events.js:277:13)\n    at IncomingMessage.emit (events.js:194:15)\n    at endReadableNT (_stream_readable.js:1103:12)\n    at process._tickCallback (internal/process/next_tick.js:63:19)"},"url":{"protocol":null,"slashes":null,"auth":null,"host":null,"port":null,"hostname":null,"hash":null,"search":null,"query":{},"pathname":"/_prometheus/metrics","path":"/_prometheus/metrics","href":"/_prometheus/metrics"},"message":"404 - {\"statusCode\":404,\"error\":\"Not Found\",\"message\":\"Not Found\"}"}
{"type":"response","@timestamp":"2019-04-09T00:01:45Z","tags":[],"pid":1,"method":"get","statusCode":500,"req":{"url":"/_prometheus/metrics","method":"get","headers":{"host":"infra.banno-staging.com","connection":"close","x-real-ip":"216.116.87.110","x-forwarded-for":"216.116.87.110","x-forwarded-host":"infra.banno-staging.com","x-forwarded-port":"443","x-forwarded-proto":"https","x-original-uri":"/kibana/_prometheus/metrics","x-scheme":"https","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3","accept-encoding":"gzip, deflate, br","accept-language":"en-US,en;q=0.9,bg;q=0.8","dnt":"1"},"remoteAddress":"172.18.0.215","userAgent":"172.18.0.215"},"res":{"statusCode":500,"responseTime":4,"contentLength":9},"message":"GET /_prometheus/metrics 500 4ms - 9.0B"}
```

**Comment by nikolay** [comment] 2019-04-09 00:31
I have `SERVER_BASEPATH` set to `/kibana` and `SERVER_REWRITEBASEPATH` to `false`.

**Comment by pjhampton** [comment] 2019-04-11 12:40
Finally managed to replicate. Will get a fix out soon 👍

**Comment by pjhampton** [comment] 2019-04-22 20:58
Sorry, time went on...

@nikolay what version are you running so I can get a release candidate out for testing? I've pushed a fix. This has nothing to do with the Kubernetes runtime (I got it wrong)

**Comment by nikolay** [comment] 2019-04-23 07:41
v6.7.1 at the moment.

**Comment by pjhampton** [comment] 2019-04-23 19:14
Thanks @nikolay 

Hopefully this solves your problem: https://github.com/pjhampton/kibana-prometheus-exporter/releases/tag/6.7.1-rc

You can download the zip first and inspect - just the master repo with an updated package version with a lot of garbage removed

**Comment by nikolay** [comment] 2019-04-25 15:47
Thank you, @pjhampton! I will test it today!

**Comment by pjhampton** [comment] 2019-05-01 11:19
hey @nikolay - I know you are insanely busy but have you had a chance to check this out as yet?

**Comment by pjhampton** [comment] 2019-05-10 23:40
Hiya @nikolay - just pinging to see if you had a chance so I can merge master back in time?

**Comment by nikolay** [comment] 2019-05-16 15:53
@pjhampton Sorry, we've been busy at work, but I'm testing it right now! Thank you for your great patience!

**Comment by nikolay** [comment] 2019-05-16 19:00
The fix worked. You should probably update the icon though!

![kibana-dashboard](https://user-images.githubusercontent.com/2882/57879658-d233ef80-77d1-11e9-8470-f864e32216b6.png)

[Here's](https://upload.wikimedia.org/wikipedia/en/3/38/Prometheus_software_logo.svg) the logo in SVG format, but if you want, I can do it for you.

**Comment by nikolay** [comment] 2019-05-16 19:01
The logo size also looks smaller and the 'Prometheus` text is misaligned. Let me dig into that, too!

**Comment by nikolay** [comment] 2019-05-16 19:15
I made the logo 32x32 px, optimized it, and made it white:

```svg
<?xml version="1.0" encoding="utf-8"?>
<svg version="1.1" x="0px" y="0px" width="32px" height="32px" viewBox="0 0 32 32" xmlns="http://www.w3.org/2000/svg">
  <path style="fill-opacity: 1; fill: rgb(255, 255, 255);" id="path4486" d="M 16 0 C 7.164 0 0 7.163 0 16 C 0 24.836 7.164 31.999 16 31.999 C 24.836 31.999 32 24.836 32 16 C 32 7.163 24.836 0 16 0 Z M 16 29.945 C 13.486 29.945 11.448 28.266 11.448 26.195 L 20.553 26.195 C 20.553 28.265 18.514 29.945 16 29.945 Z M 23.519 24.952 L 8.48 24.952 L 8.48 22.225 L 23.52 22.225 L 23.52 24.952 Z M 23.465 20.822 L 8.523 20.822 C 8.473 20.765 8.423 20.708 8.375 20.65 C 6.835 18.781 6.473 17.805 6.121 16.81 C 6.115 16.778 7.987 17.193 9.315 17.492 C 9.315 17.492 9.998 17.65 10.997 17.832 C 10.038 16.708 9.469 15.278 9.469 13.818 C 9.469 10.61 11.929 7.808 11.041 5.542 C 11.905 5.613 12.829 7.365 12.891 10.105 C 13.809 8.837 14.194 6.519 14.194 5.098 C 14.194 3.627 15.163 1.919 16.133 1.86 C 15.268 3.285 16.356 4.506 17.324 7.535 C 17.687 8.673 17.64 10.588 17.92 11.802 C 18.013 9.28 18.447 5.6 20.047 4.329 C 19.341 5.929 20.152 7.932 20.706 8.894 C 21.6 10.447 22.142 11.624 22.142 13.849 C 22.142 15.341 21.591 16.746 20.662 17.844 C 21.719 17.645 22.448 17.467 22.448 17.467 L 25.879 16.797 C 25.88 16.797 25.381 18.847 23.465 20.822 Z"/>
</svg>
```

**Comment by nikolay** [comment] 2019-05-16 19:16
I see that all other icons are straight in SVG - maybe this is how you should use this as well instead of making it a PNG.

**Comment by nikolay** [comment] 2019-05-16 19:20
@pjhampton Please, see above! Thanks!

**Comment by pjhampton** [comment] 2019-05-16 19:27
@nikolay 🙇 ❤️ 💛 🙇 Thanks so much! I agree regarding the icon - this will look way better. 
I'll ping you when I have updated this all.

**Comment by nikolay** [comment] 2019-05-16 20:58
You know what, maybe the icon should be an outline one, not sold. Let me try to make it look like the standard ones!

**Comment by nikolay** [comment] 2019-05-16 21:05
Okay, here it is:

```svg
<?xml version="1.0" encoding="utf-8"?>
<svg version="1.1"  width="32" height="32" viewBox="0 0 32 32" xmlns="http://www.w3.org/2000/svg">
  <path stroke="white" fill-opacity="0" d="M 16 0 C 7.164 0 0 7.163 0 16 C 0 24.836 7.164 31.999 16 31.999 C 24.836 31.999 32 24.836 32 16 C 32 7.163 24.836 0 16 0 Z M 16 29.945 C 13.486 29.945 11.448 28.266 11.448 26.195 L 20.553 26.195 C 20.553 28.265 18.514 29.945 16 29.945 Z M 23.519 24.952 L 8.48 24.952 L 8.48 22.225 L 23.52 22.225 L 23.52 24.952 Z M 23.465 20.822 L 8.523 20.822 C 8.473 20.765 8.423 20.708 8.375 20.65 C 6.835 18.781 6.473 17.805 6.121 16.81 C 6.115 16.778 7.987 17.193 9.315 17.492 C 9.315 17.492 9.998 17.65 10.997 17.832 C 10.038 16.708 9.469 15.278 9.469 13.818 C 9.469 10.61 11.929 7.808 11.041 5.542 C 11.905 5.613 12.829 7.365 12.891 10.105 C 13.809 8.837 14.194 6.519 14.194 5.098 C 14.194 3.627 15.163 1.919 16.133 1.86 C 15.268 3.285 16.356 4.506 17.324 7.535 C 17.687 8.673 17.64 10.588 17.92 11.802 C 18.013 9.28 18.447 5.6 20.047 4.329 C 19.341 5.929 20.152 7.932 20.706 8.894 C 21.6 10.447 22.142 11.624 22.142 13.849 C 22.142 15.341 21.591 16.746 20.662 17.844 C 21.719 17.645 22.448 17.467 22.448 17.467 L 25.879 16.797 C 25.88 16.797 25.381 18.847 23.465 20.822 Z"/>
</svg>
```

**Comment by nikolay** [comment] 2019-05-21 15:32
@pjhampton Please, use the last icon.

**Comment by pjhampton** [comment] 2019-05-21 19:19
Thanks @nikolay 😸 

https://github.com/pjhampton/kibana-prometheus-exporter/releases/tag/6.8.0

I added your latest icon in master and the above 6.X.X release. I was just screwing about yesterday with the icon on the 7 releases. It looks awesome on 6, but it's not the right fit for 7 and was just experimenting. 



Are you ok for me to delete that 6.7.1-rc, or do you need me to backport these changes before I do? I am planning to spend a weekend clearing this project up soon as it's got a bit messy and unmanagable

**Comment by pjhampton** [comment] 2019-05-21 19:21
<img width="1280" alt="Screenshot 2019-05-20 at 19 58 45" src="https://user-images.githubusercontent.com/8960296/58124283-ca2ae400-7c05-11e9-883f-97ab0a99e83c.png">

**Comment by nikolay** [comment] 2019-05-21 20:53
Yes, you can delete v6.7.1-rc. Hmmm, is this v6.8 or v7.1? It looks like they've changed completely the design in v7, so, the icon I gave you is not suitable for v7+.

**Comment by pjhampton** [comment] 2019-05-22 08:08
Yeah, they changed the design from 7 onwards again. That's cool though, we can still use that svg you rolled for everything before 7

**Comment by gracedo** [comment] 2019-08-13 21:41
Hi! I believe I may be seeing this same issue with v6.7.0 in my setup (running on Kubernetes) - would it be possible to port this fix over to v6.7.0 as well?

```
{"type":"response","@timestamp":"2019-08-13T21:15:45Z","tags":[],"pid":1,"method":"get","statusCode":404,"req":{"url":"/ops/portal/kibana/api/status?extended=","method":"get","headers":{"host":"0:5601","accept":"application/json","connection":"close"},"remoteAddress":"127.0.0.1","userAgent":"127.0.0.1"},"res":{"statusCode":404,"responseTime":1,"contentLength":9},"message":"GET /ops/portal/kibana/api/status?extended= 404 1ms - 9.0B"}
{"type":"error","@timestamp":"2019-08-13T21:15:45Z","tags":[],"pid":1,"level":"error","error":{"message":"404 - {\"statusCode\":404,\"error\":\"Not Found\",\"message\":\"Not Found\"}","name":"StatusCodeError","stack":"StatusCodeError: 404 - {\"statusCode\":404,\"error\":\"Not Found\",\"message\":\"Not Found\"}\n    at new StatusCodeError (/usr/share/kibana/plugins/kibana-prometheus-exporter/node_modules/request-promise-core/lib/errors.js:32:15)\n    at Request.plumbing.callback (/usr/share/kibana/plugins/kibana-prometheus-exporter/node_modules/request-promise-core/lib/plumbing.js:104:33)\n    at Request.RP$callback [as _callback] (/usr/share/kibana/plugins/kibana-prometheus-exporter/node_modules/request-promise-core/lib/plumbing.js:46:31)\n    at Request.self.callback (/usr/share/kibana/node_modules/request/request.js:185:22)\n    at Request.emit (events.js:189:13)\n    at Request.<anonymous> (/usr/share/kibana/node_modules/request/request.js:1161:10)\n    at Request.emit (events.js:189:13)\n    at IncomingMessage.<anonymous> (/usr/share/kibana/node_modules/request/request.js:1083:12)\n    at Object.onceWrapper (events.js:277:13)\n    at IncomingMessage.emit (events.js:194:15)\n    at endReadableNT (_stream_readable.js:1103:12)\n    at process._tickCallback (internal/process/next_tick.js:63:19)"},"url":{"protocol":null,"slashes":null,"auth":null,"host":null,"port":null,"hostname":null,"hash":null,"search":null,"query":{},"pathname":"/_prometheus/metrics","path":"/_prometheus/metrics","href":"/_prometheus/metrics"},"message":"404 - {\"statusCode\":404,\"error\":\"Not Found\",\"message\":\"Not Found\"}"}
{"type":"response","@timestamp":"2019-08-13T21:15:45Z","tags":[],"pid":1,"method":"get","statusCode":500,"req":{"url":"/_prometheus/metrics","method":"get","headers":{"host":"a9316a7e0a066417ca481d25e78f1f02-564520083.us-west-2.elb.amazonaws.com","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3","accept-encoding":"gzip, deflate, br","accept-language":"en-US,en;q=0.9","upgrade-insecure-requests":"1","x-forwarded-for":"192.168.84.64","x-forwarded-host":"a9316a7e0a066417ca481d25e78f1f02-564520083.us-west-2.elb.amazonaws.com","x-forwarded-port":"443","x-forwarded-prefix":"/ops/portal/kibana","x-forwarded-proto":"https","x-forwarded-server":"traefik-kubeaddons-6485fb848b-h26mp","x-forwarded-user":"pensive_boyd","x-real-ip":"192.168.84.64"},"remoteAddress":"192.168.34.3","userAgent":"192.168.34.3"},"res":{"statusCode":500,"responseTime":12,"contentLength":9},"message":"GET /_prometheus/metrics 500 12ms - 9.0B"}
```

**Comment by pjhampton** [comment] 2019-08-14 20:23
Hi @gracedo this has been backported https://github.com/pjhampton/kibana-prometheus-exporter/releases/tag/6.7.0

**Comment by gracedo** [comment] 2019-08-14 21:20
@pjhampton thanks so much! This works perfectly now 👍 

Only nit is that the icon is slightly smaller and misaligned - not a huge deal but in case it's easy enough to make the fix :)

![image](https://user-images.githubusercontent.com/5897740/63056212-6dedfe00-be9c-11e9-8e1f-9c94ac896c3c.png)

**Comment by pjhampton** [comment] 2019-08-15 20:49
Great, thanks @gracedo 
I'm looking at this in #77

**Comment by gracedo** [comment] 2019-08-15 21:41
I had the same thought when I was working with this yesterday! I agree that there isn't much value to having a UI for this.  I can't imagine Kibana users will be interested in seeing a bunch of prometheus-formatted metrics or know what to do with the raw data -- if anything, it might be confusing.

**Comment by pjhampton** [comment] 2019-08-16 10:48
@nikolay any opinions on this?

**Comment by dietrich-h** [comment] 2020-05-11 14:27
@pjhampton apologies for hijacking this bugtraq to contact you, was hoping to get your help with installation.  Any chance I can email you?  Thank-you

**Comment by pjhampton** [comment] 2020-05-11 14:34
Hey @dietrich-h 

Yeah, sure thing. Just open a new issue and I will help as much as I can and share my email if required. 🥇

**Closed** 2020-08-23 19:48 UTC
Labels: bug, investigation
