### ISSUE TITLE
Plugin crashes on IPv6

### ISSUE THREAD

**Issue by vladvasiliu** [pjhampton/kibana-prometheus-exporter#23] opened 2018-09-19 09:46 UTC
Hello,

The plugin seems to have a problem when Kibana is configured to listen on IPv6. Tests ran with Kibana 6.4.1.

This might likely be related to the IPv6 address which is an expected format somewhere.
I don't have time to look into it right now, but this could be of interest: https://github.com/elastic/kibana/pull/22523

Stack trace:

````
{
    "type": "error",
    "@timestamp": "2018-09-19T09:26:56Z",
    "tags": [],
    "pid": 3592,
    "level": "error",
    "error": {
        "message": "Uncaught error: Cannot read property 'overall' of undefined",
        "name": "TypeError",
        "stack": "TypeError: Uncaught error: Cannot read property 'overall' of undefined
                  at exports.default (/usr/share/kibana/plugins/kibana-prometheus-exporter/server/routes/formatter.js:5:68)
                  at getMetricsCallback (/usr/share/kibana/plugins/kibana-prometheus-exporter/server/routes/prometheus.js:22:15)
                  at Request._callback (/usr/share/kibana/plugins/kibana-prometheus-exporter/server/routes/prometheus.js:38:5)
                  at Request.self.callback (/usr/share/kibana/node_modules/request/request.js:186:22)
                  at emitTwo (events.js:126:13)
                  at Request.emit (events.js:214:7)
                  at Request.<anonymous> (/usr/share/kibana/node_modules/request/request.js:1163:10)
                  at emitOne (events.js:116:13)
                  at Request.emit (events.js:211:7)
                  at IncomingMessage.<anonymous> (/usr/share/kibana/node_modules/request/request.js:1085:12)
                  at Object.onceWrapper (events.js:313:30)
                  at emitNone (events.js:111:20)
                  at IncomingMessage.emit (events.js:208:7)
                  at endReadableNT (_stream_readable.js:1064:12)
                  at _combinedTickCallback (internal/process/next_tick.js:138:11)
                  at process._tickDomainCallback (internal/process/next_tick.js:218:9)"
    },
    "url": {
        "protocol": null,
        "slashes": null,
        "auth": null,
        "host": null,
        "port": null,
        "hostname": null,
        "hash": null,
        "search": "",
        "query": {},
        "pathname": "/_prometheus/metrics",
        "path": "/_prometheus/metrics",
        "href": "/_prometheus/metrics"
    },
    "message": "Uncaught error: Cannot read property 'overall' of undefined"
}


Debug: internal, implementation, error
    TypeError: Uncaught error: Cannot read property 'overall' of undefined
    at exports.default (/usr/share/kibana/plugins/kibana-prometheus-exporter/server/routes/formatter.js:5:68)
    at getMetricsCallback (/usr/share/kibana/plugins/kibana-prometheus-exporter/server/routes/prometheus.js:22:15)
    at Request._callback (/usr/share/kibana/plugins/kibana-prometheus-exporter/server/routes/prometheus.js:38:5)
    at Request.self.callback (/usr/share/kibana/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/share/kibana/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/usr/share/kibana/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
````

**Comment by pjhampton** [comment] 2018-09-19 12:05
Thanks @vladvasiliu 

I will pick this up when I have time.

**Comment by pjhampton** [comment] 2018-11-24 15:06
Hi @vladvasiliu 

I haven't done this before and have no way to test it. How can I build the request if all those data elements are null?

```
        "protocol": null,
        "slashes": null,
        "auth": null,
        "host": null,
        "port": null,
        "hostname": null,
        "hash": null,
        "search": "",
        "query": {},
        "pathname": "/_prometheus/metrics",
        "path": "/_prometheus/metrics",
        "href": "/_prometheus/metrics"
    },
```

**Comment by vladvasiliu** [comment] 2018-11-24 16:11
HI @pjhampton ,

I'm not sure what this URL field is, but if it's the url the plugin listens on, this might be related to a Kibana bug that made it crash on ipv6.
I'm not sure how the fixed it, especially since I'm not sure how it got there in the first place, as ipv6 had been working fine.
Here's the bug: https://github.com/elastic/kibana/issues/22451
Possibly relevant: https://github.com/elastic/kibana/pull/22469

I'm not familiar with nodejs so I have no idea where to look for this. My guess is that the IP address gets lost somewhere along the way and this bug isn't actually in your plugin but somewhere in Kibana proper.

**Comment by pjhampton** [comment] 2018-12-12 19:56
I'm going to close this guys. I can't reproduce or find any info on it. Sorry!

**Closed by pjhampton** 2018-12-12 19:56 UTC
Labels: bug
